#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        0.9  # original: 2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#set emacs as tiled
bspc rule -a Emacs state=tiled

picom -f &

~/.dotfiles/lemonbar.sh | lemonbar -p

nitrogen --set-zoom-fill ~/Pictures/Wallpapers/wall1.jpg

conky 
